### PR TITLE
Added __init__.py file to app root so that it can be imported as a module

### PR DESCRIPTION
**Pull request by palewire**
After being installed via pip and added to a Django project's ``INSTALLED_APPS`` this error appears when I run ``python manage.py migrate`` or ``python manage.py shell``.

```python
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ben/.virtualenvs/python-opencivicdata-django-test/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/ben/.virtualenvs/python-opencivicdata-django-test/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/ben/.virtualenvs/python-opencivicdata-django-test/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ben/.virtualenvs/python-opencivicdata-django-test/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/ben/.virtualenvs/python-opencivicdata-django-test/local/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named opencivicdata
```

I suspect this is because the module lacks the ``__init__.py`` file proposed here and therefore cannot be imported.

### CODE REVIEW

**Comment by jamesturk** [comment]
So this actually just came up-
https://github.com/opencivicdata/python-opencivicdata-django/pull/67

Looking at the backtrace it looks like you're using Python 2.7, which isn't
supported here.

We should be sure to clarify this (& the PEP 420 namespace package thing)
in the documentation.

**Comment by jpmckinney** [comment]
Also, `INSTALLED_APPS` should have `opencivicdata.apps.BaseConfig` not `opencivicdata`

**Comment by palewire** [comment]
Any particular reason you are forgoing Python 2.7? Seems like it would be a good thing to support if you can do it with minimum hassle.

**Comment by jamesturk** [comment]
We're using quite a few Python 3 features across the whole project: yield
from, kw only arguments, new style namespace packages, the Python 3
standard library.

This package may be easier to port than others but so far there hasn't been
a real need. if there is we could reconsider for this one package.

**Comment by jpmckinney** [comment]
Sounds like on balance the direction isn't to make this package compatible with 2.7, but can re-open if there's disagreement on that.

**Pull request closed without merging**
