### PR TITLE
added bill summary and migration

### PR DESCRIPTION
**Pull request by crdunwel**

### CODE REVIEW

**Comment by crdunwel** [comment]
:eyes: @paultag made it through tests :sunglasses:

**Comment by paultag** [comment]
@crdunwel isn't this in as `BillAbstract`? - Under http://docs.opencivicdata.org/en/latest/proposals/0006.html#implementation

Also, with field changes, we usually also update the OCDEP first :)

**Comment by crdunwel** [comment]
@paultag ahhh. I wasn't looking at the Enhancement Proposals. There was summaries attribute in the original (outdated) spec and it wasn't reflected in the current models. I'll submit a new pull request for adding a date attribute to `BillAbstract` per your suggestion.

**Comment by paultag** [comment]
:+1: thanks, @crdunwel !

**Pull request closed without merging**
