### PR TITLE
Align JURISDICTION_CLASSIFICATION_CHOICES with OCDEP

### PR DESCRIPTION
**Pull request by jpmckinney**
FYI, @fgregg, you had added `transit_authority` so this would affect you, presumably.

### CODE REVIEW

**Comment by fgregg** [comment]
can we keep `transit_authority`?

**Comment by jpmckinney** [comment]
Alternative is to change the OCDEP, but 'transit_authority' would be inconsistent with others.

**Comment by fgregg** [comment]
none of these others have ever been implemented. How about adding authority to all the others?

**Comment by jpmckinney** [comment]
Because they are not know as 'authorities'.

**Comment by fgregg** [comment]
don't really understand the problem with calling them `transit_authority`

**Comment by jpmckinney** [comment]
If there was no cost to changing the name, then consistency would be better. But I can make an exception for transit_authority since there seems to be a cost.

**Comment by fgregg** [comment]
yeah, it would require a fair amount of database surgery for me.

**Comment by fgregg** [comment]
thank you @jpmckinney

**Comment by jpmckinney** [comment]
No worries!

**Pull request merged**
