### PR TITLE
Added classficiation to EventAgendaItem model

### PR DESCRIPTION
**Pull request by patcon**
Not ready for merge (just want travis to run).

### CODE REVIEW

**Comment by patcon** [comment]
Tests seem to be passing. Review?

**Comment by jpmckinney** [comment]
So, to change these schema technically requires an Open Civic Data Enhancement Proposal: http://opencivicdata.readthedocs.org/en/latest/proposals/index.html

You mind writing one up?

**Comment by patcon** [comment]
Sure! I am all for community process

**Comment by patcon** [comment]
I started working on this, but as I was reading through the OCDEP1 and writing it up, it struck me that this doesn't seem in the spirit of the OCDEP process. And then I noticed this is explicitly mentioned:

> Examples of things that will fall under the proposal process:

> * addition of a new type to Open Civic Data
> * backwards incompatible changes to the API response format
> * significant new functionality to the API **(such as a new method, probably not a single new field in a response)**

Can I suggest this is outside that process? I'd rather spend time proposing an amendment to OCDEP1 to make that fact explicit for backward-compat field additions, if we want to keep this inside OCDEP process :)

**Comment by jpmckinney** [comment]
Good point. @jamesturk @paultag Okay to add a classification to agenda items?

@patcon You might want to consider making this an array (like some classification fields), unless you're sure you'll only ever want to have one classification per agenda item.

**Comment by patcon** [comment]
Thanks :)

I thought string seemed better, as 1) there's precedent for it in other models, and 2) the migration path from string to array is a little more straightforward. But if string classifications are legacy, and all recent ones are array, then the latter would make sense.

**Comment by jpmckinney** [comment]
My preference is to go with array. There’s precedence for both.

**Comment by patcon** [comment]
:+1:

**Comment by patcon** [comment]
I just realized we've been making updates by editting previous migration files.

Might I suggest in the future, we use a migration for each change to the models, and then, even for the small changes (ie. not using an OCDEP), the filenames give us an easy-to-grok record of changes in the models?

**Comment by jpmckinney** [comment]
Sounds reasonable!

**Comment by patcon** [comment]
squashed

**Comment by jamesturk** [comment]
I'm good w/ this but we should consider this part of 0.9.x since it breaks backwards compatibility w/ 0.8.x due to requiring a migration and there are now quite a few projects running 0.8.x in production

**Comment by patcon** [comment]
:+1:

**Comment by jpmckinney** [comment]
So, do we commit this to master, or in a branch?

**Comment by fgregg** [comment]
id vote for a branch and keep master for bug fixes for a while

**Comment by jpmckinney** [comment]
Hmm, if a release is in maintenance mode then that usually goes in the branch, so that activ development happens on master.

**Comment by fgregg** [comment]
There are different conventions.

**Comment by patcon** [comment]
What if we use feature toggles and allow next-version features to be enabled by setting an envvar or flag?

**Comment by jpmckinney** [comment]
To get things moving, I created a `0.8.x` branch. Master will be for future release.

**Pull request merged**
