### PR TITLE
Make loaddivisions idempotent

### PR DESCRIPTION
**Pull request by mileswwatkins**
Addresses https://github.com/opencivicdata/python-opencivicdata-django/issues/12

### CODE REVIEW

**Comment by rshorey** [comment]
do we have tests for this? should we?

**Comment by mileswwatkins** [comment]
Good call; I'll add an idempotency test to https://github.com/opencivicdata/python-opencivicdata-django/blob/master/opencivicdata/tests/test_loaddivisions.py

**Comment by mileswwatkins** [comment]
Let's see if Travis likes this. I tried to locally run the tests, but my model and database versions are out of whack; I'll fix 'em and try more locally if this doesn't go well.

**Comment by mileswwatkins** [comment]
@rshorey, after working on it and discussing with Labs North, I don't think there's a simple way to test that none of the database records got changed. I'm of the opinion we should merge it as-is.

**Comment by mileswwatkins** [comment]
`--force-with-lease` magics!

**Pull request merged**
