### PR TITLE
Add num_seats to Post object

### PR DESCRIPTION
**Pull request by mileswwatkins**
[_In conjunction with `pupa` PR 167_](https://github.com/opencivicdata/pupa/pull/167)

Includes a new field on the `Post` object to indicate the number of identical seats that are available therein. The `migration` file also includes the `preserve_default` field, which results from [upgrading through `Django` 1.7.1](https://docs.djangoproject.com/en/1.8/ref/migration-operations/#alterfield).

All tests running green locally, for both `python-opencivicdata-django` and `pupa` repos.

### CODE REVIEW

**Comment by rshorey** [comment]
@mileswwatkins, Is this still a thing we want to do? If so, then could you deal with merge conflicts and redo migrations, please, so they're on top of the current set? Otherwise let's close this.

**Comment by mileswwatkins** [comment]
Good call. Closing for now, although I'm not opposed to re-opening in the future.

**Comment by rshorey** [comment]
cool, I think since this is a small change in terms of lines of code, we should just rebuild it at a time when we'll be able to check it and get it integrated quickly so we don't have to figure out a mess of migrations.

**Comment by jpmckinney** [comment]
If this gets revived, we can pick a better field name than `num_seats` as I [wrote](https://github.com/opencivicdata/pupa/pull/167#issuecomment-103699438)

> num_seats is undesirable because (1) we avoid abbreviations, (2) Posts are not always seats, (3) it's ambiguous as to whether it's the number of currently held or possibly held Posts.

**Pull request closed without merging**
