### PR TITLE
migrate to django 1.8, drop arrayfield, uuidfield, and jsonfield

### PR DESCRIPTION
**Pull request by jamesturk**
**very dangerous, not intended for merge yet**

merging this will require rebuilding the database from scratch, if desirable I think it should be possible to make a script that will do this migration as a one-off but **migrations have been reset** to avoid retaining old dependencies  forever

other issues:
* this removes the extras column from OCDBase, this will break pupa

### CODE REVIEW

**Comment by jamesturk** [comment]
merge this into pupa first https://github.com/opencivicdata/pupa/pull/183

need to take a look at imago too

**Comment by apendleton** [comment]
For JSON in Invisible Influence, I've found the JSON field in https://bitbucket.org/schinckel/django-postgres/ to be great, and not to have the issues that either of the other JSON fields we had used before had. It does mean a hard requirement on Postgres 9.4, though, since it uses JSONB behind the scenes.

**Comment by jamesturk** [comment]
thanks, looks pretty good to me.  

@paultag should I update this PR w/ django-postgres' json field?  we'd likely want to drop the dependency (which would mean another migration reset unfortunately) once Django 1.9 is out but I don't think there's any reason it'd require a recreation of a DB

**Comment by paultag** [comment]
Yeah SGTM

**Comment by paultag** [comment]
(Right, back on a real line!)

Yeah, that sounds great; since it's all just jsonb under the hood, I'm sure we can handle the migration in a sane way :)

Anyway, :+1: on it!

**Comment by jamesturk** [comment]
is django-postgres pip installable?    if not I'm not sure if we want to
introduce a dependency for pupa on it, I don't think there's a way to
specify a non PyPI dependency in setup.py

I'll defer to @paultag

On Wed, May 20, 2015 at 9:25 AM, <notifications@github.com> wrote:

> (Right, back on a real line!)
>
> Yeah, that sounds great; since it's all just jsonb under the hood, I'm
> sure we can handle the migration in a sane way :)
>
> Anyway, [image: :+1:] on it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/python-opencivicdata-django/pull/42#issuecomment-103887926>
> .
>



-- 

James Turk
Labs Director | Sunlight Foundation <http://www.sunlightfoundation.com/>
202-558-8723 | @JamesTurk <https://twitter.com/jamesturk>

[image: Sunlight Foundation] <http://sunlightfoundation.com/>

**Comment by paultag** [comment]
Uch; I wish they would push to pypi

**Comment by paultag** [comment]
https://pypi.python.org/pypi/django-postgres isn't even owned by that guy; which might be why; let me file a ticket

**Comment by paultag** [comment]
Filed @ https://bitbucket.org/schinckel/django-postgres/issue/6/release-to-pypi - let me review the rest

**Comment by jamesturk** [comment]
OK

assuming we want to go w/ django-postgres in some capacity there's now 

https://github.com/opencivicdata/python-opencivicdata-django/tree/django1.8-nouuid-nojson-oksomejson

**Comment by jamesturk** [comment]
there's always this option 

http://www.scotttorborg.com/python-packaging/dependencies.html#packages-not-on-pypi

**Comment by paultag** [comment]
I'm going to try to pull the tablecloth out from under the app here

**Comment by paultag** [comment]
OK, so dealing with all the parts on their own was a mess.

New plan: Update to Django 1.8 *without* changing all that much. Then, preform the migration, keeping the dependency on the old fields.

After that's up, we can use the new Django 1.8 squashmigrations feature to drop the old migrations, and be happy, but I think trying to pull that off with 1.7 alone might be nasty.

I'll start a cherry pick against this

**Comment by paultag** [comment]
OK, I cherry picked chunks of this which @rshorey cherry picked into her branch. It's in master now with a half-migration. Closing this one!

**Comment by paultag** [comment]
(Thanks!)

**Pull request closed without merging**
