### PR TITLE
add pending to bill relation types

### PR DESCRIPTION
**Pull request by fgregg**

### CODE REVIEW

**Comment by paultag** [comment]
Hurm.

So, what are we to have Pupa to do here?

**Comment by fgregg** [comment]
We need a post-write hook for rewriting these flags https://github.com/opencivicdata/pupa/issues/86

**Comment by jpmckinney** [comment]
Why set a relation type at all until one is known? Could you not leave it blank?

**Comment by fgregg** [comment]
@jpmckinney good question.

**Comment by jpmckinney** [comment]
Closing as the proposed relation type seems to represent an internal software state, not a fact about the real world. Can re-open if not the case.

**Pull request closed without merging**
