### PR TITLE
[WIP] Document Model

### PR DESCRIPTION
**Pull request by fgregg**
Legislatures handle, officially, a lot of documents that are not bills, like reports and communications. 

In addition, this model should act as the base model for campaign finance models.

Related: https://github.com/opencivicdata/docs.opencivicdata.org/pull/50

### CODE REVIEW

**Comment by fgregg** [comment]
@jamesturk @jpmckinney would you mind taking a look at this WIP PR. This feels very duplicative. Should there be a base class that both bill and document inherit from? I'm not a great at Django, so advice really appreciated.

**Comment by jpmckinney** [comment]
I haven't looked in detail, but I think Bill should inherit from a more generic Document model. If you want to add properties to that document superclass that would not make sense on Bill, then perhaps we can have an AbstractDocument class, from which Bill and Document inherit.

**Comment by fgregg** [comment]
@jpmckinney, I've spent some time going down this road and I don't think it's really possible because of the way that we are defining model `id`. 

Say we define a base model like

```python
class Document(OCDBase):
    identifier = models.CharField(max_length=100)

    title = models.TextField()

    classification = ArrayField(base_field=models.TextField(), blank=True, default=list)      # check that array values are in enum?
    subject = ArrayField(base_field=models.TextField(), blank=True, default=list)
```

and two subclasses.

```python
class Bill(Document) :
    id = OCDIDField(ocd_type='bill')
    from_organization = models.ForeignKey(Organization, 
                                          related_name='bills',
                                          null=True)
    legislative_session = models.ForeignKey(LegislativeSession, 
                                            related_name='bills')
    ...

class Filing(Document) :
    id = OCDIDField(ocd_type='filing')
    from_organization = models.ForeignKey(Organization, 
                                          related_name='filings',
                                          null=True)
    ...

```
This doesn't work because we get an error like: 

```python
django.core.exceptions.FieldError: Local field 'id' in class 'Bill' clashes with field of similar name from base class 'Document'
```

We can have ```Document``` be an abstract model, and will help some with DRY, but we will need to have things like

```python
class DocumentAbstract(RelatedBase):
    abstract = models.TextField()
    note = models.TextField(blank=True)
    date = models.TextField(max_length=10, blank=True)  # YYYY[-MM[-DD]]

    class Meta:
        abstract = True

class BillAbstract(DocumentAbstract):
        bill = models.ForeignKey(Bill, related_name='abstracts')

class FilingAbstract(DocumentAbstract):
        filing = models.ForeignKey(Filing, related_name='abstracts')
```

Which is better than fully repeating all the methods. Thoughts? Other approaches?

**Comment by jpmckinney** [comment]
An abstract class seems reasonable to me. @jamesturk is more an expert at Django than me, though.

**Comment by fgregg** [comment]
oops, the related_name will have to be different too. like

```python
class BillAbstract(DocumentAbstract):
        bill = models.ForeignKey(Bill, related_name='bill_abstracts')

class FilingAbstract(DocumentAbstract):
        filing = models.ForeignKey(Filing, related_name='filing_abstracts')
```

**Comment by jpmckinney** [comment]
What happens if the `related_name`'s are the same?

**Comment by fgregg** [comment]
they can't be the same. django throws an error.

**Comment by jamesturk** [comment]
sorry for getting to this so late.  I think an abstract class is the way to go, I'm not 100% sure I understand renaming all of the related_names though, since Bill and Document are different concrete classes it shouldn't be necessary.  related names on two different classes wouldn't conflict

**Comment by fgregg** [comment]
Note to self: Create full text class that includes information about encoding.

**Pull request closed without merging**
