### PR TITLE
Add bill action classification for "Received By Committee"

### PR DESCRIPTION
**Pull request by patcon**
Toronto's Council and committees vote to receive informational agenda items (their proxy for bills).

See: http://www1.toronto.ca/wps/portal/contentonly?vgnextoid=e26d0f1025c21410VgnVCM10000071d60f89RCRD&vgnextchannel=9632acb640c21410VgnVCM10000071d60f89RCRD#agenda

cc: @jpmckinney

### CODE REVIEW

**Comment by jpmckinney** [comment]
I would drop the `committee-` prefix and make the description more general.

> Received - Council has received the recommendations for information only and will take no further action.

**Comment by patcon** [comment]
Sure. Just did it for consistency with `executive-received`. Should they be merged then, or is it preferred to have `received` and `executive-received`?

**Comment by jpmckinney** [comment]
I don't know the history of `executive-received`, but both council and committee can receive, and I'd rather not have even more `*-received` unless there's a clear reason to do so.

**Comment by patcon** [comment]
:+1: done and done

**Comment by jpmckinney** [comment]
LGTM. @jamesturk, @paultag Do you have any recollection of the `executive-received` classification?

**Comment by patcon** [comment]
> but both council and committee can receive

Slight aside, but were you saying that council isn't a committee @jpmckinney? If so, is `committee-referral` best-suited as `referral`, in the same vein?

**Comment by jpmckinney** [comment]
Seems like it. Council is not a [committee](https://en.wikipedia.org/wiki/Committee).

**Comment by jpmckinney** [comment]
Ok, so `executive-received` makes sense, because it's a step in a formal process, e.g. in Canada you'd have:

* `reading-1`
* `reading-2`
* `committee-referral`
* `committee-passage`
* `reading-3`
* `executive-received` (not tracked)
* `executive-signature` (Royal Assent)

So, whether you prefix `referral` or `received` with `legislature-` or `committee-` depends on whether you can fit those steps into a predictable process.

**Comment by patcon** [comment]
Hm. So is it just me, or is there some inconsistency.

`execute-received` = received by executive
`committee-passage` = passed by committee
`committee-referral` = presumably referred to committee, if it's the only referral?

Straight-up `referral` sounds more reasonable, as it's usually the main body that refers to committee, right? Or at the very least, it's equal opportunity, and the main body and committees can refer things around. It's a wierd "acting on" vs "acting by" switch that happens for that action classification...

Thoughts?

**Comment by jpmckinney** [comment]
I think an issue can get referred to the Supreme Court, or to an officer of parliament, etc. - it's not the usual course of business. I don't rely on this logic, so I'd like input from people for whom it matters.

**Comment by patcon** [comment]
totally fair. cc @fgregg

**Comment by fgregg** [comment]
`committee-referral

**Comment by patcon** [comment]
:+1: on the @fgregg's suggestion

Still would make sense for a general referral though, as SF for one has lots of referrals to departments and city staff. Come to think of it, so does Toronto.

**Comment by patcon** [comment]
@fgregg I think you accidentally editted your comment and deleted it?

**Comment by patcon** [comment]
OK, so it sounds like this could have 3 to-dos:
- [ ] rename `committee-referral` to `referral-committee`
- [ ] add `referral` (for referring to non-committee things, like departments or staff)
- [ ] add `received` (ie. for non-committees like council receiving items)

I'll create a separate PRs, if no objections or clarifications

**Comment by jpmckinney** [comment]
I don't think we need separate PRs for all three. We just need agreement. I'd like input from @jamesturk or @paultag, especially re: renaming an existing classification, which could break deployed code.

**Comment by fgregg** [comment]
The change from committee-referral to referral-committee will break some of
our code, but I'm okay with the change.

**Comment by patcon** [comment]
Ah. Rats. While we're at it, should we use the verb for referral? We kinda have an assortment of formats, sometimes using verbs ("received", "deferred") and sometimes nouns ("referral", "passage")

So we could just kinda standardize things all at once:
- "committee-referral" changes to "referred-committee"
- add "referred", which sits nicely with "deferred" and "received"
- now "committee-passage" and "committee-failure" are different, so not sure if we'd want to pull the band-aid and consider using "passed", "failed", etc.

Or we could take the opposite tack and move to using "deferral", "receipt".

Or we could just leave it as-is and accept the inconsistency.

**Comment by fgregg** [comment]
Let's keep this small.

**Comment by jpmckinney** [comment]
There are only three verbs: `amended`, `executive-received` and `deferred`. I'm in favor of the smallest change, and that would mean going for nouns.

**Comment by patcon** [comment]
Agree on smallness. Does the current diff work? Not exactly as suggested by James, but ready for review.

**Comment by jpmckinney** [comment]
For consistency with the majority of classifications, I would use nouns, so `referral`, `referral-committee`, and `receipt`.

**Comment by jamesturk** [comment]
I think if everyone here is OK w/ renames it is OK as nobody else has
deployed code that I'm aware of.

Going forward it's something to avoid for sure so I'd be in favor of
standardizing them w/ this opportunity.

**Comment by jpmckinney** [comment]
K, the maximum change to increase consistency would also include:

* amendment-amended -> amendment-amendment (not awesome, but consistent)
* executive-received -> executive-receipt
* deferred -> deferral

**Comment by patcon** [comment]
kinda gets a little weird with human-readable copy, but otherwise fine:

```py
('deferral', 'Deferral or Tabling'),
```

Honestly, I'm just going to create two PRs, each entirely consistent one way or the other, and someone can merge whichever one seems better :)

**Comment by jpmckinney** [comment]
The human copy can be whatever - no code should depend on those values.

**Comment by patcon** [comment]
ok, i think that encompasses everything mentioned

**Comment by jpmckinney** [comment]
LGTM

**Comment by jpmckinney** [comment]
@fgregg @jamesturk OK to merge?

**Comment by jamesturk** [comment]
Looking this over, not to nitpick, but why did referral-committee switch order?  Doesn't that make it inconsistent w/ other committee actions?

**Comment by jpmckinney** [comment]
My understanding is that `committee-referral` is not an action taken by a committee, but rather by a chamber.

**Comment by jamesturk** [comment]
OK :+1:

**Pull request merged**
