### PR TITLE
Merge objects

### PR DESCRIPTION
**Pull request by rshorey**
Need to determine what to do with overlap with @boblannon's pupa PR: https://github.com/opencivicdata/pupa/pull/170

### CODE REVIEW

**Comment by boblannon** [comment]
My opinion is that we go with your merge code.  Mine is pretty brutal and makes sweeping policy decisions based on my particular usecase (the disclosures and related objects).  That usecase isn't going to even exist in the future, as we'll be linking influence records, rather than merging them.

**Comment by paultag** [comment]
What are all the migrations that get added here?

**Comment by rshorey** [comment]
@paultag adding a locked_fields field to everything

**Comment by paultag** [comment]
Yeah, I saw a few of those, but a bunch don't have locked_fields in the name, e.g.

```python

+        migrations.AlterField(
+            model_name='billaction',
+            name='organization',
+            field=models.ForeignKey(to='opencivicdata.Organization', related_name='actions'),
+            preserve_default=True,
+        ), 
```

**Comment by rshorey** [comment]
It looks like I may have changed the default? I don't remember doing that for this change, but this might be a Rachel-is-terrible-at-git issue where I did it somewhere else but failed to commit that merge? I will investigate

**Comment by paultag** [comment]
It may also be a Django migrations hiccup, but yeah, let's at least explain
what's up here :)

On Mon, Jun 22, 2015 at 12:28 PM, Rachel <notifications@github.com> wrote:

> It looks like I may have changed the default? I don't remember doing that
> for this change, but this might be a Rachel-is-terrible-at-git issue where
> I did it somewhere else but failed to commit that merge? I will investigate
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/python-opencivicdata-django/pull/46#issuecomment-114171669>
> .
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Comment by paultag** [comment]
(Perhaps we just need two migrations to logically swap out this if there's a need for it)

**Comment by rshorey** [comment]
it looks like somehow the related names didn't get set in the initial migration. Seems like these are all that. Any idea why it would add those in?

**Comment by rshorey** [comment]
to be clear, I definitely did not change any related names.

**Comment by paultag** [comment]
@rshorey Let's get a new PR open with just the related name migration

**Comment by rshorey** [comment]
OK, coming shortly. There are some char and text fields in here too which I'm pretty confident are a result of a previous migration file not being appropriately shared

**Comment by rshorey** [comment]
@paultag I think this is ready to go, unless you, @mileswwatkins or @boblannon has any objections.

**Comment by paultag** [comment]
Awesome. let's do it!

**Comment by mileswwatkins** [comment]
:confetti_ball:

**Pull request merged**
