### PR TITLE
divisions now have a valid_through date

### PR DESCRIPTION
**Pull request by rshorey**
using the --reset flag on loaddivisions will ensure that divisions are re-imported with new info. otherwise that only happens when the count changes.

### CODE REVIEW

**Comment by mileswwatkins** [comment]
My PR to this Singularity bug should make `loaddivisions` check even without a flag. Since we run `loaddivisions` so rarely, I think there's no harm in having it compare the two lists every time. What're your thoughts?
https://github.com/opencivicdata/python-opencivicdata-django/issues/12

**Comment by rshorey** [comment]
@mileswwatkins did you add valid_through to the model as well? If not, we should incorporate that into your PR and then close this one, I think.

**Comment by mileswwatkins** [comment]
My other PRs deal with `Boundary`s, not `Division`s so much. My memory's a bit fuzzy; could you clarify why do `Division`s need `valid_through`? And why wouldn't they also need `valid_from`?

**Comment by rshorey** [comment]
@mileswwatkins did we decide we're ditching this PR?

**Comment by mileswwatkins** [comment]
Totes. Were you nuking and re-building your OCD database? If so, did you have a migration PR for 1.7 –> 1.8? Let me know if/how I can help out with reviewing.

**Pull request closed without merging**
